removed tfvars from apply
 Error: Can't set variables when applying a saved plan
The -var and -var-file options cannot be used when applying a saved plan file, because a saved plan includes the variable values that were set when it was created.